FROM resty-dev

RUN apt-get update -yq && \
    apt-get install -yq git-core

# Wrong
RUN luarocks install luafilesystem && \
    luarocks install penlight && \
    luarocks install say && \
    luarocks install luasocket && \
    luarocks install luasec && \
    luarocks install luassert && \
    luarocks install lua_cliargs && \
    luarocks install dkjson && \
    luarocks install luasystem && \
    luarocks install mediator_lua && \
    luarocks install lua-term && \
    luarocks install sha1 && \
    luarocks install md5 && \
    luarocks install busted

COPY ./tests /root
COPY ./src /root/src
RUN chmod +x /root/run_tests.sh

WORKDIR /root
ENTRYPOINT /root/run_tests.sh